## Campo magnético produzido por um enrolamento percorrido por uma corrente eléctrica
## Lei de Faraday

In [54]:
# Retrieve libraries
from __future__ import print_function
import matplotlib.pyplot as plt
import numpy as np
from scipy import constants 
%matplotlib inline


In [55]:
# B-field in a center of a coil Equ 6
def BfieldZ(i,r,n):
    return constants.mu_0 *n * i /2/r

# B-field in the z axys of a coil Equ 7
def Axys_factor(r,z):
    return (1 + (z/r)**2)**(-3.0/2)


# B-field in the z axys of a coil Equ 7
def BfieldZ_axys(i,r,n,z):
    bz0=BfieldZ(i,r,n)
    bz = bz0 * Axys_factor(r,z)# (1 + (z/r)**2)**(-3.0/2)
    return bz


In [56]:
#Enrolamento de campo
N=2000; R = 0.07; I =1; 
print("Campo %g T" %BfieldZ(I,R,N) )

Campo 0.017952 T


In [60]:
# Quadro 2 Amplitude da Corrente
def Ienr(e0,r):
    return e0/r
R1=10e3; Renr= 830
V=np.array([4,6,8,10])
I=Ienr(V,R1+Renr)
#I*1e3 #print("Ienr %g mA" %(I*1e3) )
I

array([0.00036934, 0.00055402, 0.00073869, 0.00092336])

In [58]:
# Campo B esperado no centro da bobine em T
BfieldZ(I,R,N)

array([6.63045541e-06, 9.94568311e-06, 1.32609108e-05, 1.65761385e-05])

In [59]:
# Quadro 3, Fem na Sonda
def femT(V2,r2,ris):
    return V2*(r2+ris)/r2
R2=10e3;Ris=220
femT(1,R2,Ris)


1.022

In [41]:
# Quadro 3 Campo B triangular Equ. 22
Freq=50.0; T=1.0/Freq
def Btriang(e, T,nt, rt,angle):
    return T*e/4/nt/np.pi/rt**2/np.cos(angle)
NT=2000;RT=0.00175;
Btriang(I, T,NT, RT,0)

array([9.59722272e-05, 1.43958341e-04, 1.91944454e-04, 2.39930568e-04])

In [53]:
# Ponto 3.5
Freq=100
Cnts19= constants.mu_0/2*N*NT*np.pi*RT**2/R*2*np.pi
Cnts19*Freq
I35=Ienr(10,R1+Renr)
eT=Cnts19*I35*Freq

z=np.array([ 0,1,2,3,4,5,8,10,15])*0.01
eTz=eT*Axys_factor(R,z)
eTz

array([2.00409914e-04, 1.94427779e-04, 1.78155616e-04, 1.55622121e-04,
       1.31172648e-04, 1.07985574e-04, 5.72262986e-05, 3.77949625e-05,
       1.51561005e-05])